<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Owner-PC" name="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest" tests="100" failures="0" timestamp="10 Oct 2016 15:28:10 GMT" time="67.175" errors="95">
  <testcase name="agentAccountPurchaseDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountPurchaseDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountPurchaseDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentAccountPurchaseDate -->
  <testcase name="institutionAccountDomesticPrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDomesticPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDomesticPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountDomesticPrice -->
  <testcase name="paymentOrderHistoryUnitPrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryUnitPrice -->
  <testcase name="paypalLogin" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paypalLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paypalLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paypalLogin -->
  <testcase name="institutionPayPalAccount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionPayPalAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionPayPalAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionPayPalAccount -->
  <testcase name="addCourseToCart" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- addCourseToCart -->
  <testcase name="cartAdditionalFeesTitle" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartAdditionalFeesTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartAdditionalFeesTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- cartAdditionalFeesTitle -->
  <testcase name="studentAccountPurchaseDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountPurchaseDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountPurchaseDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountPurchaseDate -->
  <testcase name="reviewOrderProductUnitPrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderProductUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderProductUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderProductUnitPrice -->
  <testcase name="reviewOrderAdditionalFeesTitle" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderAdditionalFeesTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderAdditionalFeesTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderAdditionalFeesTitle -->
  <testcase name="institutionAccountDisplayedTotalCommissionPercent" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDisplayedTotalCommissionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDisplayedTotalCommissionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountDisplayedTotalCommissionPercent -->
  <testcase name="agentAccountTotalRevenue" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountTotalRevenue()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountTotalRevenue()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentAccountTotalRevenue -->
  <testcase name="paymentOrderHistoryLinePrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryLinePrice -->
  <testcase name="agentAccountDisplayedTotalCommissionPercent" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountDisplayedTotalCommissionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountDisplayedTotalCommissionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentAccountDisplayedTotalCommissionPercent -->
  <testcase name="checkAggregateFeesEqualPaymentOrderHistoryTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkAggregateFeesEqualPaymentOrderHistoryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkAggregateFeesEqualPaymentOrderHistoryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkAggregateFeesEqualPaymentOrderHistoryTotal -->
  <testcase name="studentAccountStartDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountStartDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountStartDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountStartDate -->
  <testcase name="studentAccountAdditionalFee" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountAdditionalFee()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountAdditionalFee()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountAdditionalFee -->
  <testcase name="studentPaymentStatus" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentPaymentStatus()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentPaymentStatus()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentPaymentStatus -->
  <testcase name="studentAccountCourseName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountCourseName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountCourseName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountCourseName -->
  <testcase name="reviewOrderTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderTotal -->
  <testcase name="eduInstitutionPayPalAccountInstitutionCommission" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.eduInstitutionPayPalAccountInstitutionCommission()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.eduInstitutionPayPalAccountInstitutionCommission()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- eduInstitutionPayPalAccountInstitutionCommission -->
  <testcase name="checkoutInstitutionTitle" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutInstitutionTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutInstitutionTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutInstitutionTitle -->
  <testcase name="getCourseList" time="11.158" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest"/>
  <testcase name="agentAccountTotalPrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountTotalPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountTotalPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentAccountTotalPrice -->
  <testcase name="institutionAccountAdditionalFeeName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountAdditionalFeeName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountAdditionalFeeName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountAdditionalFeeName -->
  <testcase name="reviewOrderHeader" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderHeader()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderHeader()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderHeader -->
  <testcase name="paymentOrderHistoryAdditionalFees" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryAdditionalFees -->
  <testcase name="institutionLogout" time="0.001" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionLogout -->
  <testcase name="studentPayPalAccount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentPayPalAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentPayPalAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentPayPalAccount -->
  <testcase name="reviewOrderAdditionalFees" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderAdditionalFees -->
  <testcase name="institutionAccountDisplayedAgentPercent" time="0.001" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDisplayedAgentPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDisplayedAgentPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountDisplayedAgentPercent -->
  <testcase name="agentPaymentStatus" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentPaymentStatus()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentPaymentStatus()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentPaymentStatus -->
  <testcase name="reviewOrderProductName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderProductName -->
  <testcase name="enterInstitutionLoginDetails" time="13.663" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest"/>
  <testcase name="getCourseFees" time="2.563" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="org.openqa.selenium.NoSuchElementException" message="Unable to locate element: {&quot;method&quot;:&quot;id&quot;,&quot;selector&quot;:&quot;edit-field-finish-date-und-0-value-datepicker-popup-0&quot;}
Command duration or timeout: 1.94 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;2.48.2&#039;, revision: &#039;41bccdd10cf2c0560f637404c2d96164b67d9d67&#039;, time: &#039;2015-10-09 13:08:06&#039;
System info: host: &#039;Owner-PC&#039;, ip: &#039;192.168.0.111&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_45&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=40.0, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 6e42fe14-f292-4dfc-8ec0-94a979fe7a73
*** Element info: {Using=id, value=edit-field-finish-date-und-0-value-datepicker-popup-0}">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"edit-field-finish-date-und-0-value-datepicker-popup-0"}
Command duration or timeout: 1.94 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'Owner-PC', ip: '192.168.0.111', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=40.0, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 6e42fe14-f292-4dfc-8ec0-94a979fe7a73
*** Element info: {Using=id, value=edit-field-finish-date-und-0-value-datepicker-popup-0}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:403)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
	at Unipupil.TestFramework.pageObjects.InternationalCourse.getCourseFees(InternationalCourse.java:54)
	at Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest.getCourseFees(FirefoxBuyCourseAdditionalFeesAgentInternationalTest.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"edit-field-finish-date-und-0-value-datepicker-popup-0"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'Owner-PC', ip: '192.168.0.111', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/Owner/AppData/Local/Temp/anonymous1629707207780859650webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
	at <anonymous class>.FirefoxDriver.prototype.findElement(file:///C:/Users/Owner/AppData/Local/Temp/anonymous1629707207780859650webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/Owner/AppData/Local/Temp/anonymous1629707207780859650webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/Owner/AppData/Local/Temp/anonymous1629707207780859650webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/Owner/AppData/Local/Temp/anonymous1629707207780859650webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
]]>
    </error>
  </testcase> <!-- getCourseFees -->
  <testcase name="completeOrderPageMessage" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.completeOrderPageMessage()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.completeOrderPageMessage()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- completeOrderPageMessage -->
  <testcase name="institutionAccountAdditionalFeeTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountAdditionalFeeTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountAdditionalFeeTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountAdditionalFeeTotal -->
  <testcase name="selectInstitution" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- selectInstitution -->
  <testcase name="goToCourseEditPage" time="13.844" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest"/>
  <testcase name="reviewOrderInstitutionTitle" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderInstitutionTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderInstitutionTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderInstitutionTitle -->
  <testcase name="institutionAccountFinishDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountFinishDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountFinishDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountFinishDate -->
  <testcase name="findInstitution" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.findInstitution()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.findInstitution()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- findInstitution -->
  <testcase name="goToHomepage" time="14.106" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest"/>
  <testcase name="institutionAccountAdditionalFee" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountAdditionalFee()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountAdditionalFee()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountAdditionalFee -->
  <testcase name="institutionLogin" time="11.838" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest"/>
  <testcase name="checkoutAdditionalFeesTitle" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutAdditionalFeesTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutAdditionalFeesTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutAdditionalFeesTitle -->
  <testcase name="checkCartSubTotalAgainstGrossFees" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkCartSubTotalAgainstGrossFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkCartSubTotalAgainstGrossFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkCartSubTotalAgainstGrossFees -->
  <testcase name="aggregateFeesEqualReviewOrderSubTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.aggregateFeesEqualReviewOrderSubTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.aggregateFeesEqualReviewOrderSubTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- aggregateFeesEqualReviewOrderSubTotal -->
  <testcase name="reviewOrderLinePrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderLinePrice -->
  <testcase name="paymentOrderHistoryProductDescription" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryProductDescription()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryProductDescription()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryProductDescription -->
  <testcase name="adminLogin" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.adminLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.adminLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- adminLogin -->
  <testcase name="displayedAgentCommissionPercent" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.displayedAgentCommissionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.displayedAgentCommissionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- displayedAgentCommissionPercent -->
  <testcase name="eduInstitutionPayPalAccountGrossFees" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.eduInstitutionPayPalAccountGrossFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.eduInstitutionPayPalAccountGrossFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- eduInstitutionPayPalAccountGrossFees -->
  <testcase name="goToCheckout" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.goToCheckout()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.goToCheckout()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- goToCheckout -->
  <testcase name="selectCourse" time="0.001" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.selectCourse()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.selectCourse()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- selectCourse -->
  <testcase name="paymentOrderHistoryTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryTotal -->
  <testcase name="reviewOrderSubTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderSubTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.reviewOrderSubTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrderSubTotal -->
  <testcase name="checkoutLineProductName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutLineProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutLineProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutLineProductName -->
  <testcase name="cartProductUnitPrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartProductUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartProductUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- cartProductUnitPrice -->
  <testcase name="cartLinePrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- cartLinePrice -->
  <testcase name="studentAccountAdditionalFeeTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountAdditionalFeeTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountAdditionalFeeTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountAdditionalFeeTotal -->
  <testcase name="checkAggregateFeesEqualCheckoutTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkAggregateFeesEqualCheckoutTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkAggregateFeesEqualCheckoutTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkAggregateFeesEqualCheckoutTotal -->
  <testcase name="checkoutAdditionalFees" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutAdditionalFees -->
  <testcase name="checkoutTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutTotal -->
  <testcase name="enterAddressAndContinue" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.enterAddressAndContinue()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.enterAddressAndContinue()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- enterAddressAndContinue -->
  <testcase name="paymentOrderHistoryPage" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryPage()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryPage()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryPage -->
  <testcase name="institutionAccountDisplayedInstitutionPercent" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDisplayedInstitutionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountDisplayedInstitutionPercent()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountDisplayedInstitutionPercent -->
  <testcase name="institutionAccountStartDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountStartDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountStartDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountStartDate -->
  <testcase name="institutionAccountTotalPaid" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountTotalPaid()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountTotalPaid()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountTotalPaid -->
  <testcase name="completeOrderTitle" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.completeOrderTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.completeOrderTitle()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- completeOrderTitle -->
  <testcase name="checkInstitutionAccount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkInstitutionAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkInstitutionAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkInstitutionAccount -->
  <testcase name="checkoutLinePrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutLinePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutLinePrice -->
  <testcase name="agentLogin" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentLogin -->
  <testcase name="paymentOrderHistoryQuantity" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryQuantity()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryQuantity()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryQuantity -->
  <testcase name="eduInstitutionPayPalAccountAgentCommission" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.eduInstitutionPayPalAccountAgentCommission()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.eduInstitutionPayPalAccountAgentCommission()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- eduInstitutionPayPalAccountAgentCommission -->
  <testcase name="institutionAccountOverviewPage" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountOverviewPage()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountOverviewPage()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountOverviewPage -->
  <testcase name="agentAccountTotalPaid" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountTotalPaid()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountTotalPaid()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentAccountTotalPaid -->
  <testcase name="paymentOrderHistoryProductName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryProductName -->
  <testcase name="cartProductName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartProductName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- cartProductName -->
  <testcase name="ppLoginPageSummaryTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppLoginPageSummaryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppLoginPageSummaryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- ppLoginPageSummaryTotal -->
  <testcase name="studentAccountAdditionalFeeName" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountAdditionalFeeName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountAdditionalFeeName()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountAdditionalFeeName -->
  <testcase name="studentAccountFinishDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountFinishDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountFinishDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountFinishDate -->
  <testcase name="studentLogin" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentLogin()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentLogin -->
  <testcase name="ppConfirmPayment" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppConfirmPayment()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppConfirmPayment()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- ppConfirmPayment -->
  <testcase name="paymentOrderHistoryHeader" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryHeader()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.paymentOrderHistoryHeader()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- paymentOrderHistoryHeader -->
  <testcase name="submitOrder" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.submitOrder()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.submitOrder()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- submitOrder -->
  <testcase name="cartAdditionalFees" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.cartAdditionalFees()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- cartAdditionalFees -->
  <testcase name="agentPayPalAccount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentPayPalAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentPayPalAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentPayPalAccount -->
  <testcase name="enterStudentLoginDetails" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- enterStudentLoginDetails -->
  <testcase name="studentAccountCoursePrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountCoursePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.studentAccountCoursePrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentAccountCoursePrice -->
  <testcase name="institutionAccountPurchaseDate" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountPurchaseDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionAccountPurchaseDate()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionAccountPurchaseDate -->
  <testcase name="ppConfirmPageSummaryAmount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppConfirmPageSummaryAmount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppConfirmPageSummaryAmount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- ppConfirmPageSummaryAmount -->
  <testcase name="ppConfirmPageSummaryTotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppConfirmPageSummaryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppConfirmPageSummaryTotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- ppConfirmPageSummaryTotal -->
  <testcase name="ppLoginPageSummaryAmount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppLoginPageSummaryAmount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.ppLoginPageSummaryAmount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- ppLoginPageSummaryAmount -->
  <testcase name="agentAccountAgentCommission" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountAgentCommission()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.agentAccountAgentCommission()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- agentAccountAgentCommission -->
  <testcase name="checkoutProductUnitPrice" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutProductUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkoutProductUnitPrice()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkoutProductUnitPrice -->
  <testcase name="goToStudentAccount" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.goToStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.goToStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- goToStudentAccount -->
  <testcase name="getCommissionPercentages" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.getCommissionPercentages()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.getCommissionPercentages()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- getCommissionPercentages -->
  <testcase name="checkAggregateFeesEqualCartSubtotal" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkAggregateFeesEqualCartSubtotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.checkAggregateFeesEqualCartSubtotal()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkAggregateFeesEqualCartSubtotal -->
  <testcase name="institutionPaymentStatus" time="0.000" classname="Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest">
    <error type="java.lang.Throwable" message="Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionPaymentStatus()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method FirefoxBuyCourseAdditionalFeesAgentInternationalTest.institutionPaymentStatus()[pri:0, instance:Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionPaymentStatus -->
</testsuite> <!-- Unipupil.UniMavenTests.FirefoxBuyCourseAdditionalFeesAgentInternationalTest -->
